#!/bin/bash

#SBATCH --job-name=d2q9-bgk
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=28
#SBATCH --time=00:10:00
#SBATCH --partition=veryshort
#SBATCH --output=d2q9-bgk_n112.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable as a Flat MPI program
#mpirun -l -print-rank-map -binding -map-by=socket ./d2q9-bgk input_128x128.params obstacles_128x128.dat
#mpirun -l -print-rank-map -binding -map-by=socket ./d2q9-bgk input_128x256.params obstacles_128x256.dat
#mpirun -l -print-rank-map -binding -map-by=socket ./d2q9-bgk input_256x256.params obstacles_256x256.dat
mpirun -l -print-rank-map -binding -map-by=socket ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
